// Regenerate src/content/media-manifest.ts by listing the photos/ tree of the
// "christian-alain" bucket for the CURRENT environment (reads .env.local/.env
// via @next/env). imageUrl() uses the manifest to decide whether a section has
// a real photo (→ Supabase) or should fall back to picsum.
//
//   npm run media:manifest      # → whatever .env.local points at (local by default)
//
// Non-fatal: if the bucket can't be listed (stack down, missing creds), it
// leaves the existing manifest untouched so a transient error never wipes it.
import { writeFile } from "node:fs/promises"
import path from "node:path"
import { loadEnvConfig } from "@next/env"
import { createClient } from "@supabase/supabase-js"
import { MEDIA_BUCKET } from "../src/lib/media"

loadEnvConfig(process.cwd())

const url = process.env.SUPABASE_URL ?? process.env.NEXT_PUBLIC_SUPABASE_URL
const key =
  process.env.SUPABASE_SECRET_KEY ?? process.env.SUPABASE_SERVICE_ROLE_KEY

const MANIFEST_PATH = path.join(process.cwd(), "src/content/media-manifest.ts")

async function main(): Promise<void> {
  if (!url || !key) {
    console.warn("media:manifest — no Supabase creds; leaving manifest unchanged.")
    return
  }
  const supabase = createClient(url, key, { auth: { persistSession: false } })

  // Recurse the bucket (Supabase lists one folder level at a time; subfolders
  // come back with a null id, files have an id + metadata).
  const listAll = async (prefix: string): Promise<string[]> => {
    const out: string[] = []
    const { data, error } = await supabase.storage
      .from(MEDIA_BUCKET)
      .list(prefix, { limit: 1000 })
    if (error) throw error
    for (const item of data ?? []) {
      const full = prefix ? `${prefix}/${item.name}` : item.name
      if (item.id === null) out.push(...(await listAll(full)))
      else out.push(full)
    }
    return out
  }

  let keys: string[]
  try {
    keys = (await listAll("photos")).sort()
  } catch (err) {
    console.warn(
      `media:manifest — could not list bucket (${(err as Error).message}); manifest unchanged.`,
    )
    return
  }
  const body =
    `// AUTO-GENERATED by scripts/gen-media-manifest.ts — do not edit by hand.\n` +
    `// Storage keys present under photos/ in the "${MEDIA_BUCKET}" bucket for the\n` +
    `// environment this was generated against. imageUrl() (src/content/image.ts)\n` +
    `// serves these and falls back to picsum for any seed not listed here.\n` +
    `// Regenerate with \`npm run media:manifest\` (or \`npm run media:sync\`).\n` +
    `export const MEDIA_MANIFEST: string[] = ${JSON.stringify(keys, null, 2)}\n`
  await writeFile(MANIFEST_PATH, body)
  console.log(`media:manifest — wrote ${keys.length} keys from ${url} / ${MEDIA_BUCKET}.`)
}

main().catch((err) => {
  console.warn("media:manifest — unexpected error; manifest unchanged:", err)
})
