// AUTO-GENERATED by scripts/gen-media-manifest.ts — do not edit by hand.
// Storage keys present under photos/ in the "christian-alain" bucket for the
// environment this was generated against. imageUrl() (src/content/image.ts)
// serves these and falls back to picsum for any seed not listed here.
// Regenerate with `npm run media:manifest` (or `npm run media:sync`).
//
// Committed empty: it's an env-specific build artifact. `npm run media:sync`
// regenerates it locally; the Vercel build regenerates it against prod.
export const MEDIA_MANIFEST: string[] = []
